import type { ExpenseStore } from "./types";

export const demoStore: ExpenseStore = {
  categories: [
    {
      id: "cat-subscriptions",
      userId: "demo",
      name: "Suscripciones",
      icon: "Sparkles",
      tone: "violet",
    },
    {
      id: "cat-services",
      userId: "demo",
      name: "Servicios",
      icon: "WalletCards",
      tone: "blue",
    },
    {
      id: "cat-transport",
      userId: "demo",
      name: "Transporte",
      icon: "Car",
      tone: "orange",
    },
    {
      id: "cat-personal",
      userId: "demo",
      name: "Personal",
      icon: "HeartPulse",
      tone: "green",
    },
    {
      id: "cat-general",
      userId: "demo",
      name: "General",
      icon: "WalletCards",
      tone: "slate",
    },
  ],
  templates: [
    {
      id: "exp-movistar",
      userId: "demo",
      name: "Movistar",
      description: "Linea y fibra",
      amount: 60,
      currency: "EUR",
      categoryId: "cat-services",
      tags: ["internet", "telefono"],
      startDate: "2026-01-08",
      dueDay: 8,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-game-pass",
      userId: "demo",
      name: "Game Pass",
      description: "Suscripcion gaming",
      amount: 12,
      currency: "EUR",
      categoryId: "cat-subscriptions",
      tags: ["gaming"],
      startDate: "2026-01-12",
      dueDay: 12,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-deudas-sam",
      userId: "demo",
      name: "Deudas Sam",
      description: "Pago mensual",
      amount: 60,
      currency: "EUR",
      categoryId: "cat-general",
      tags: ["deuda"],
      startDate: "2026-01-01",
      dueDay: 1,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-parking",
      userId: "demo",
      name: "Parking",
      description: "Garaje",
      amount: 30,
      currency: "EUR",
      categoryId: "cat-transport",
      tags: ["parking", "coche"],
      startDate: "2026-01-01",
      dueDay: 1,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-gasolina",
      userId: "demo",
      name: "Gasolina",
      description: "Estimacion mensual",
      amount: 65,
      currency: "EUR",
      categoryId: "cat-transport",
      tags: ["coche"],
      startDate: "2026-01-01",
      dueDay: 1,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-1password",
      userId: "demo",
      name: "1password",
      description: "Password manager",
      amount: 4,
      currency: "EUR",
      categoryId: "cat-subscriptions",
      tags: ["software"],
      startDate: "2026-01-15",
      dueDay: 15,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-icloud",
      userId: "demo",
      name: "Icloud",
      description: "Almacenamiento",
      amount: 3.99,
      currency: "EUR",
      categoryId: "cat-subscriptions",
      tags: ["apple"],
      startDate: "2026-01-15",
      dueDay: 15,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-dazn",
      userId: "demo",
      name: "Dazn",
      description: "Deportes",
      amount: 15,
      currency: "EUR",
      categoryId: "cat-subscriptions",
      tags: ["deporte"],
      startDate: "2026-01-15",
      dueDay: 15,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-macrofactor",
      userId: "demo",
      name: "Macrofactor",
      description: "App nutricion",
      amount: 12,
      currency: "EUR",
      categoryId: "cat-personal",
      tags: ["salud"],
      startDate: "2026-01-10",
      dueDay: 10,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-codex",
      userId: "demo",
      name: "Codex",
      description: "AI coding",
      amount: 90,
      currency: "EUR",
      categoryId: "cat-subscriptions",
      tags: ["ia", "software"],
      startDate: "2026-01-06",
      dueDay: 6,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-youtube",
      userId: "demo",
      name: "Youtube",
      description: "Premium",
      amount: 15,
      currency: "EUR",
      categoryId: "cat-subscriptions",
      tags: ["streaming"],
      startDate: "2026-01-02",
      dueDay: 2,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-el-corte-ingles",
      userId: "demo",
      name: "El corte ingles",
      description: "Compra financiada",
      amount: 90,
      currency: "EUR",
      categoryId: "cat-general",
      tags: ["compra"],
      startDate: "2026-01-01",
      dueDay: 1,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-netflix",
      userId: "demo",
      name: "Netflix",
      description: "Streaming",
      amount: 25,
      currency: "EUR",
      categoryId: "cat-subscriptions",
      tags: ["streaming"],
      startDate: "2026-01-01",
      dueDay: 1,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-gym",
      userId: "demo",
      name: "Gym",
      description: "Gimnasio",
      amount: 50,
      currency: "EUR",
      categoryId: "cat-personal",
      tags: ["salud"],
      startDate: "2026-01-01",
      dueDay: 1,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
  ],
  overrides: [
    {
      id: "ovr-macrofactor-jun",
      userId: "demo",
      templateId: "exp-macrofactor",
      occurrenceDate: "2026-06-10",
      status: "paid",
      paidAt: "2026-06-10T12:00:00.000Z",
      amountPaid: 12,
    },
    {
      id: "ovr-codex-jun",
      userId: "demo",
      templateId: "exp-codex",
      occurrenceDate: "2026-06-06",
      status: "paid",
      paidAt: "2026-06-06T12:00:00.000Z",
      amountPaid: 90,
    },
    {
      id: "ovr-youtube-jun",
      userId: "demo",
      templateId: "exp-youtube",
      occurrenceDate: "2026-06-02",
      status: "paid",
      paidAt: "2026-06-02T12:00:00.000Z",
      amountPaid: 15,
    },
    {
      id: "ovr-el-corte-ingles-jun",
      userId: "demo",
      templateId: "exp-el-corte-ingles",
      occurrenceDate: "2026-06-01",
      status: "paid",
      paidAt: "2026-06-01T12:00:00.000Z",
      amountPaid: 90,
    },
    {
      id: "ovr-netflix-jun",
      userId: "demo",
      templateId: "exp-netflix",
      occurrenceDate: "2026-06-01",
      status: "paid",
      paidAt: "2026-06-01T12:00:00.000Z",
      amountPaid: 25,
    },
    {
      id: "ovr-gym-jun",
      userId: "demo",
      templateId: "exp-gym",
      occurrenceDate: "2026-06-01",
      status: "paid",
      paidAt: "2026-06-01T12:00:00.000Z",
      amountPaid: 50,
    },
  ],
};
