import type { ExpenseStore } from "./types";

export const demoStore: ExpenseStore = {
  categories: [
    {
      id: "cat-subscriptions",
      userId: "demo",
      name: "Suscripciones",
      icon: "Sparkles",
      tone: "violet",
    },
    {
      id: "cat-home",
      userId: "demo",
      name: "Vivienda",
      icon: "Home",
      tone: "blue",
    },
    {
      id: "cat-transport",
      userId: "demo",
      name: "Transporte",
      icon: "Car",
      tone: "orange",
    },
    {
      id: "cat-health",
      userId: "demo",
      name: "Salud",
      icon: "HeartPulse",
      tone: "green",
    },
    {
      id: "cat-general",
      userId: "demo",
      name: "General",
      icon: "WalletCards",
      tone: "slate",
    },
  ],
  templates: [
    {
      id: "exp-netflix",
      userId: "demo",
      name: "Netflix",
      description: "Plan familiar",
      amount: 17.99,
      currency: "EUR",
      categoryId: "cat-subscriptions",
      tags: ["streaming", "familia"],
      startDate: "2026-01-12",
      dueDay: 12,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-rent",
      userId: "demo",
      name: "Alquiler",
      description: "Pago vivienda",
      amount: 860,
      currency: "EUR",
      categoryId: "cat-home",
      tags: ["casa"],
      startDate: "2026-01-01",
      dueDay: 1,
      recurrence: { frequency: "monthly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
    {
      id: "exp-car-insurance",
      userId: "demo",
      name: "Seguro coche",
      description: "Cuota trimestral",
      amount: 148.5,
      currency: "EUR",
      categoryId: "cat-transport",
      tags: ["coche", "seguro"],
      startDate: "2026-03-18",
      dueDay: 18,
      recurrence: { frequency: "quarterly" },
      active: true,
      createdAt: "2026-01-01T09:00:00.000Z",
      updatedAt: "2026-01-01T09:00:00.000Z",
    },
  ],
  overrides: [],
};
